
export const schools = [
    'Esc. Industrial sgo Maradona (J.M gorriti S/N)',
'Esc. N° 4 Maria eva de Peron (Guemes y Parana)',
'Esc N° 1128 Fuerza Area (B° Autonomia)',
'Esc. N° 765 (libertad 2085 B° libertad)',
'Esc. Jose Ingeniero (chaco y defensa)',
'Esc. Laprida (Rivadavia 390)',
'Esc. Jose Hernandez (G. Iramain 9850 B° Gorostiaga)',
'Instituto Nuestra sra de loreto (B° General Paz calle 103 y Gregorio iramain)',
'Esc. Tecnica N° 1 (Av. Belgrano y A. Alvarez)',
'Esc. Primaria Huaico Hondo N° 88 Borges ( Av Belgrano 1746)',
'Esc. Benjamin Santillan N1241 ( Capdevilla de reto B° Coesa)',
'Esc. Castiglione (C. Lorenzini N° 449 B J. Newbery)',
'Colegio San francisco (Olachea 549)',
'Colegio La asuncion (Av. Belgrano S 1063)',
'Esc. Henry Dunant (Santa Fe prolongacion S/N B° Tradicion)',
'Esc. Sarmiento (Independencia y Alsina)',
'UNSE (Av. Belgrano 1912)',
'Esc. Nac.Comercio Prof. A Ferreyra (A. Alvarez 155)',
'Esc. Sra. De fatima (Buenos Aires 2455)',
'Colegio Herman de Brujin (Av. Alsina Este)',
'Esc. 1329 Raul Alfonsin (B. Siglo XXI)',
'Esc. ISPP 1 Prof. Rodolfo Diaz (Av.Colon y colect. Raul Alfonsin)',
'Esc. N 1132(Av. 67 B° ejercito Argentino)',
'Esc. 1240 del Bicentenario (B° Siglo XXI Sector duplex)',
'Esc. N° 33 Nuestra Sra de mercedes (Av. Aguirre N° 1457)',
'Esc. N° 1243 V del carmen',
'Esc. N 718 Maria Auxiliadora (B° SMATA)',
'Colegio Santa Lucia (leopoldo lugones y San marcos S/N)',
'Jardin de Infantes N 804 (B° 7 ampliacion mariano moreno)',
'Escuela N 54 Juan Neirot '
]